version: '3'

services:
  pexad:
    image: pexacoin/core:latest
    build:
      context: .
    volumes:
      - /home/pexa/.pexa:/root/.pexa
    ports:
      - 18770:18770
      - 8235:8235

  # Pexa Coin Build and Release Tools
  devtools:
    image: pexacoin/devtools:latest
    build:
      context: .
      dockerfile: .docker/devtools/Dockerfile
    volumes:
      - .:/usr/local/bin/pexa
      - ~/releases:/releases
      - ./.docker/devtools/release.sh:/usr/local/bin/release.sh
